name: calling
description: Shared one-on-one calling functionality for the Video Chat MVP.
version: 0.0.1

environment:
  sdk: ^3.13.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  livekit_client: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
